package by.epam.karotki.film_rating.controller;

public enum CommandName {
	AUTHORIZATION, REGISTRATION, LOCALIZATION, NEWFILMS, FILM_CARD,
	AUTHOR_CARD, SIGN_OUT, UNKNOWN_COMMAND, PROFILE, ADD_FILM, ADD_AUTHOR,
	COMMENT_LIST, ACCOUNT_LIST,ADD_COMMENT, FILMS_BY_GENRE, UPDATE_ACCOUNT_PAGE,
	UPDATE_ACCOUNT, REG_PAGE, FILMS_BY_YEAR, FILMS_BY_RATE, FILM_FAVORITE, UPDATE_COMMENT,
	DELETE_ACCOUNT,ADD_FILM_PAGE;
}
