package by.epam.karotki.film_rating.controller;

public enum CommandName {
	LOCALIZATION, UNKNOWN_COMMAND,
	AUTHORIZATION, REGISTRATION, SIGN_OUT, PROFILE, ACCOUNT_LIST, UPDATE_ACCOUNT, DELETE_ACCOUNT,
	NEWFILMS, FILMS_BY_GENRE, FILMS_BY_YEAR, FILMS_BY_RATE, FILM_FAVORITE,
	FILM_CARD, ADD_FILM, UPDATE_FILM, DELETE_FILM,
	AUTHOR_CARD, ADD_AUTHOR, DELETE_AUTHOR,
	COMMENT_LIST, ADD_COMMENT, UPDATE_COMMENT, DELETE_COMMENT,
	UPDATE_ACCOUNT_PAGE, UPDATE_FILM_PAGE, REG_PAGE, ADD_FILM_PAGE, ADD_AUTHOR_PAGE;
	 
}
